
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateComponentDescriptorH.js
 */

#pragma once

#include <react/renderer/core/ConcreteComponentDescriptor.h>
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <react/renderer/components/view/ViewShadowNode.h>
#include "Props.h"
#include "EventEmitters.h"

namespace facebook {
namespace react {
extern const char FastImageViewComponentName[] = "FastImageView";
using FastImageViewShadowNode =
    ConcreteViewShadowNode<FastImageViewComponentName, FastImageViewProps, FastImageViewEventEmitter>;

class ComponentDescriptorParameters;
class ComponentDescriptor;

class FastImageViewComponentDescriptor final : public ConcreteComponentDescriptor<FastImageViewShadowNode> {
public:
    FastImageViewComponentDescriptor(ComponentDescriptorParameters const &parameters)
        : ConcreteComponentDescriptor(parameters) {}
};

} // namespace react
} // namespace facebook
