
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateEventEmitterCpp.js
 */

#include "EventEmitters.h"

namespace facebook {
namespace react {

void FastImageViewEventEmitter::onLoadStart(OnLoadStart event) const
{
  dispatchEvent("loadStart", [event=std::move(event)](jsi::Runtime &runtime) {
    auto payload = jsi::Object(runtime);
    return payload;
  });
}
void FastImageViewEventEmitter::onProgress(OnProgress event) const
{
  dispatchEvent("progress", [event=std::move(event)](jsi::Runtime &runtime) {
    auto payload = jsi::Object(runtime);
    payload.setProperty(runtime, "loaded", event.loaded);
    payload.setProperty(runtime, "total", event.total);
    return payload;
  });
}
void FastImageViewEventEmitter::onLoad(OnLoad event) const
{
  dispatchEvent("load", [event=std::move(event)](jsi::Runtime &runtime) {
    auto payload = jsi::Object(runtime);
    payload.setProperty(runtime, "width", event.width);
    payload.setProperty(runtime, "height", event.height);
    return payload;
  });
}
void FastImageViewEventEmitter::onError(OnError event) const
{
  dispatchEvent("error", [event=std::move(event)](jsi::Runtime &runtime) {
    auto payload = jsi::Object(runtime);
    return payload;
  });
}
void FastImageViewEventEmitter::onLoadEnd(OnLoadEnd event) const
{
  dispatchEvent("loadEnd", [event=std::move(event)](jsi::Runtime &runtime) {
    auto payload = jsi::Object(runtime);
    return payload;
  });
}

} // namespace react
} // namespace facebook
