
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsCpp.js
 */

#include "Props.h"
#include <react/renderer/core/PropsParserContext.h>
#include <react/renderer/core/propsConversions.h>

namespace facebook {
namespace react {

FastImageViewProps::FastImageViewProps(
    const PropsParserContext &context,
    const FastImageViewProps &sourceProps,
    const RawProps &rawProps): ViewProps(context, sourceProps, rawProps),

    source(convertRawProp(context, rawProps, "source", sourceProps.source, {})),
    isWebpGif(convertRawProp(context, rawProps, "isWebpGif", sourceProps.isWebpGif, {false})),
    resizeWidth(convertRawProp(context, rawProps, "resizeWidth", sourceProps.resizeWidth, {})),
    imgStyleHeight(convertRawProp(context, rawProps, "imgStyleHeight", sourceProps.imgStyleHeight, {})),
    resizeMode(convertRawProp(context, rawProps, "resizeMode", sourceProps.resizeMode, {ResizeMode::COVER})),
    defaultSource(convertRawProp(context, rawProps, "defaultSource", sourceProps.defaultSource, {})),
    tintColor(convertRawProp(context, rawProps, "tintColor", sourceProps.tintColor, {}))
      {}

} // namespace react
} // namespace facebook
