
/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GeneratePropsH.js
 */

#include "RNCFastImageViewTurboModule.h"

using namespace rnoh;
using namespace facebook;

static jsi::Value __hostFunction_RNCFastImageViewTurboModule_preload(
    jsi::Runtime &rt,
    react::TurboModule &turboModule,
    const jsi::Value *args, size_t count){
    return static_cast<ArkTSTurboModule &>(turboModule).call(rt, "preload", args, count);
}

static jsi::Value __hostFunction_RNCFastImageViewTurboModule_clearMemoryCache(
    jsi::Runtime &rt, 
    react::TurboModule &turboModule, 
    const jsi::Value* args, 
    size_t count)
{
  return static_cast<ArkTSTurboModule &>(turboModule).callAsync(rt, "clearMemoryCache", args, count);
}

static jsi::Value __hostFunction_RNCFastImageViewTurboModule_clearDiskCache(
    jsi::Runtime &rt, 
    react::TurboModule &turboModule, 
    const jsi::Value* args, 
    size_t count)
{
  return static_cast<ArkTSTurboModule &>(turboModule).callAsync(rt, "clearDiskCache", args, count);
}

RNCFastImageViewTurboModule::RNCFastImageViewTurboModule(const ArkTSTurboModule::Context ctx, const std::string name)
  : ArkTSTurboModule(ctx, name)
{
    methodMap_["preload"] = MethodMetadata {0, __hostFunction_RNCFastImageViewTurboModule_preload};
    methodMap_["clearMemoryCache"] = MethodMetadata {0, __hostFunction_RNCFastImageViewTurboModule_clearMemoryCache};
    methodMap_["clearDiskCache"] = MethodMetadata {0, __hostFunction_RNCFastImageViewTurboModule_clearDiskCache};
}