/*
 * Copyright (c) 2024 Huawei Device Co., Ltd. All rights reserved
 * Use of this source code is governed by a MIT license that can be
 * found in the LICENSE file.
 */

/**
 * This code was generated by [react-native-codegen](https://www.npmjs.com/package/react-native-codegen).
 *
 * Do not edit this file as changes may cause incorrect behavior and will be lost
 * once the code is regenerated.
 *
 * @generated by codegen project: GenerateShadowNodeH.js
 */

#pragma once
#include "Props.h"
#include "States.h"
#include "EventEmitters.h"
#include <react/renderer/components/view/ConcreteViewShadowNode.h>
#include <jsi/jsi.h>

namespace facebook {
namespace react {

JSI_EXPORT extern const char FastImageViewComponentName[];

/*
 * `ShadowNode` for <FastImageView> component.
 */
using FastImageViewShadowNode = ConcreteViewShadowNode<
    FastImageViewComponentName,
    FastImageViewProps,
    FastImageViewEventEmitter,
    FastImageViewState>;

} // namespace react
} // namespace facebook
